### ISSUE TITLE
there is some problem is the program quine.c

### ISSUE THREAD

**Issue by AndroidInternal** [MakeNowJust/quine#1]
i run this code,the output is not equal to the source code totally...(in the last part)
it seems due to the "$c" where i cant figure out now in my opnion...

**Comment by makenowjust** [comment]
Your environment is Windows?

`%m$` format is specified in POSIX . But Windows's runtime didn't implement it.

You can run such a source as Quine. But I don't replace, because such a source is larger than before.

```
#include<stdio.h>
int main(void){char*s="#include<stdio.h>%cint main(void){char*s=%c%s%c;printf(s,10,34,s,34,10);return 0;}%c";printf(s,10,34,s,34,10);return 0;}
```
