### ISSUE TITLE
PureScript quine xD

### ISSUE THREAD

**Issue by Javran** [MakeNowJust/quine#3]
@paf31 wrote a quine for PureScript [here](https://gist.github.com/paf31/22f2513e0f11c80d79a0)

**Comment by makenowjust** [comment]
Thank @Javran request new language!

But, I have two policies.
1. I put Quines written by only me in this repository.
2. These Quines can execute on command line (stdio).

Does PureScript satisfy policy 2?

**Comment by Javran** [comment]
Wow I just happen to know your 1st policy, I have to say it's an impressive work!

PureScript compiles to Javascript,  so you need something like `psc Main.purs --main=Main | node` from command line.

**Comment by makenowjust** [comment]
Thanks!  I immediately write Quine in PureScript.

**Comment by makenowjust** [comment]
Write up! https://github.com/MakeNowJust/quine/blob/master/quine.purs

**Comment by Javran** [comment]
:+1:  I guess this issue can be closed now.
